#!/usr/bin/env python

"""
Likes tweets with a certain hashtag
"""

# imports
import os, time, json
from sys import exit
from urlparse import urlparse
from contextlib import contextmanager
import tweepy
import backoff

# import exceptions
from urllib2 import HTTPError

def log(**kwargs):
    print ' '.join( "{0}={1}".format(k,v) for k,v in sorted(kwargs.items()) )


@contextmanager
def measure(**kwargs):
    start = time.time()
    status = {'status': 'starting'}
    log(**dict(kwargs.items() + status.items()))
    try:
        yield
    except Exception, e:
        status = {'status': 'err', 'exception': "'{0}'".format(e)}
        log(**dict(kwargs.items() + status.items()))
        raise
    else:
        status = {'status': 'ok', 'duration': time.time() - start}
        log(**dict(kwargs.items() + status.items()))


def fav_tweet(api,tweet,like_min):
	"""Attempt to fav a tweet and return True if successful"""

	#QA: don't like if too low
	if tweet.favorite_count < like_min:
		log(at='filter', reason='too unpopular', tweet=tweet.favorite_count)
		return

	# sometimes this raises TweepError even if reply.favorited
	# was False
	try:
		api.create_favorite(id=tweet.id)
	except tweepy.TweepError, e:
		log(at='fav_error', tweet=tweet.id, klass='TweepError', msg="'{0}'".format(str(e)))
		return False

	log(at='favorite', tweet=tweet.id)
	return True

@backoff.on_exception(backoff.expo, tweepy.TweepError, max_tries=8)
	
def fetch_hashtag_tweets(api,target_hashtag):
	"""Fetch tweets with hashtag from twitter"""
	with measure(at='fetch_hashtag'):
		hashtag_tweets = api.search(q=target_hashtag, result_type='recent', count=100)
	return hashtag_tweets

def main():
    log(at='main')
    main_start = time.time()

    validate_env()

    owner_username    = os.environ.get('TW_OWNER_USERNAME')
    username          = os.environ.get('TW_USERNAME')
    consumer_key      = os.environ.get('TW_CONSUMER_KEY')
    consumer_secret   = os.environ.get('TW_CONSUMER_SECRET')
    access_key        = os.environ.get('TW_ACCESS_TOKEN')
    access_secret     = os.environ.get('TW_ACCESS_TOKEN_SECRET')
	like_min          = os.environ.get('TW_Like_Min')
	target_hashtag_one    = 'indiedev'
	target_hashtag_two    = 'gamedev'

    auth = tweepy.OAuthHandler(consumer_key=consumer_key,
        consumer_secret=consumer_secret)
    auth.set_access_token(access_key, access_secret)

    api = tweepy.API(auth_handler=auth, retry_count=3)
	tweet_Search_One = fetch_hashtag_tweets(api,target_hashtag_one)
	tweet_Search_Two = fetch_hashtag_tweets(api,target_hashtag_two)

    for tweet in tweet_Search_One:
	
        try:
            fav_tweet(api,tweet,like_min)
        except HTTPError, e:
            log(at='rt_error', klass='HTTPError', code=e.code(), body_size=len(e.read()))
            debug_print(e.code())
            debug_print(e.read())
        except Exception, e:
            log(at='rt_error', klass='Exception', msg="'{0}'".format(str(e)))
            raise
			
    for tweet in tweet_Search_Two:
	
        try:
            fav_tweet(api,tweet,like_min)
        except HTTPError, e:
            log(at='rt_error', klass='HTTPError', code=e.code(), body_size=len(e.read()))
            debug_print(e.code())
            debug_print(e.read())
        except Exception, e:
            log(at='rt_error', klass='Exception', msg="'{0}'".format(str(e)))
            raise


    log(at='finish', status='ok', duration=time.time() - main_start)
